//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 07:09:55 PM COT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://parameta.com/soapservice/compiled/employee", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.parameta.soapservice.compiled.employee;
